### ISSUE TITLE
conflicting dependencies between optax and jaxlib

### ISSUE THREAD

**Issue by enosair** [ikostrikov/implicit_q_learning#3]
Hi, I got the following error when running `pip install -r ./requirements.txt`

The conflict is caused by:
    optax 0.0.9 depends on jaxlib>=0.1.37
    optax 0.0.8 depends on jaxlib>=0.1.37
    optax 0.0.6 depends on jaxlib>=0.1.37

Could you please take a look? Thank you.

**Comment by ikostrikov** [comment]
I cannot reproduce the issue on Ubuntu 20.04 and python 3.8.

What OS and python version are you using?

**Comment by enosair** [comment]
Hi, thanks for the prompt reply. I'm using Ubuntu 20.04.1 and Python
3.10.0.

**Comment by ikostrikov** [comment]
It seems that jaxlib does not support python 3.10 yet:
https://github.com/google/jax/issues/8279

**Comment by enosair** [comment]
> It seems that jaxlib does not support python 3.10 yet: [google/jax#8279](https://github.com/google/jax/issues/8279)
> 
> See available releases at https://storage.googleapis.com/jax-releases/jax_releases.html

Got it. I downgraded to python 3.8 and can solve this issue.  However I hit another problem during installing gym[mujoco] -- it was looking for mujoco150 but I have mujoco200. 

I ignored that line and manually installed the other packages, now I can run your code.

**Comment by enosair** [comment]
When I try to install jaxlib with cuda support, it automatically upgrade my jax to 0.2.24. Is it possible to use jax 0.2.21 (as specified in your requirements.txt) with GPU?

**Comment by ikostrikov** [comment]
I've added cuda instructions to the readme. I'm sorry for the confusion. Also, the instructions in jaxrl were incorrect. I fixed them there as well.
