### ISSUE TITLE
A question about the toy umaze environment in Figure 2?

### ISSUE THREAD

**Issue by fuyw** [ikostrikov/implicit_q_learning#7]
Hi Ilya,

May I ask about the toy umaze environment in Figure 2.

Is this a self-defined environment, or is it the `antmaze-umaze` environment in D4RL?

And how do we generate the offline dataset?

Many thanks.

**Comment by ikostrikov** [comment]
Hi,

No, it's not in d4rl.

You can find it here:
https://colab.research.google.com/drive/1s2kS-pDoo2EIdL1YmxGzV8ai_7dunGWu?usp=sharing

**Comment by fuyw** [comment]
Thanks so much.
